### ISSUE TITLE
Onright and onwrong bug

### ISSUE THREAD

**Issue by eminyazan** [JayTWWM/Quiz-View-Flutter#1]
I have two variable dogru and yanlıs when you gave right answer dogru++ when you gave wrong answer yanlis++ I created my quiz view page with carouselslider library. The problem is when you click an answer page change to next page ıf you answered the last question you can see your whole results. But when you slide to previous page user can click right answer or rwrong answer so ı ask to user 10 question for example he gave 15 right answer. Any advices ? Thank you.

`

CarouselSlider.builder(
                carouselController: _carouselController,
                itemCount: _sorular.length,
                options: CarouselOptions(
                  height: Get.mediaQuery.size.height*0.8,
                  autoPlay: false,
                  disableCenter: false,
                  enableInfiniteScroll: false,
                  viewportFraction: 1,
                  enlargeCenterPage: true,
                ),
                itemBuilder: (context, index) {
                  return QuizView(
                    showCorrect: false,
                    tagBackgroundColor: Colors.deepOrange,
                    tagColor: Colors.black,
                    answerColor: Colors.white,
                    answerBackgroundColor: Color.fromARGB(255, 255, 0, 111),
                    questionColor: Colors.white,
                    backgroundColor: Color.fromARGB(255, 111, 0, 255),
                    width: _pageWidth*0.97,
                    height: _pageHeight*0.7,
                    question: _sorular[index].soru,
                    rightAnswer: _sorular[index].dogru,
                    wrongAnswers: [
                      _sorular[index].yanlis1,
                      _sorular[index].yanlis2,
                      _sorular[index].yanlis3
                    ],
                    onRightAnswer: (){
                      _dogru++;
                      if(index+1!=_sorular.length){
                        _carouselController.nextPage();
                      }else{
                        showDialog(
                            barrierDismissible: false,
                            context: context,
                            builder: (context) {
                              return AlertDialog(
                                title: Text("Sorular Bitti"),
                                content: Text("Sonuçları Getiriyoruz..."),
                                actions: [
                                  FlatButton(
                                    onPressed: _goSonuclarEkran(_sorular.length,_dogru,_yanlis,widget.userid),
                                    child: Text(""),
                                  ),
                                ],
                              );
                            });
                      }
                    },
                    onWrongAnswer: () {
                      _yanlis++;
                      if(index+1!=_sorular.length){
                        _carouselController.nextPage();
                      }else{
                        showDialog(
                            barrierDismissible: false,
                            context: context,
                            builder: (context) {
                              return AlertDialog(
                                title: Text("Sorular Bitti"),
                                content: Text("Sonuçları Getiriyoruz..."),
                                actions: [
                                  FlatButton(
                                    onPressed: _goSonuclarEkran(_sorular.length,_dogru,_yanlis,widget.userid),
                                    child: Text(""),
                                  ),
                                ],
                              );
                            });
                      }
                    }
                  );
                },
              ),`

**Comment by JayTWWM** [comment]
I think you should keep a book which checks if it is already answered or not!
Closing the issue because it's not on the pub side.
