### ISSUE TITLE
Right answer appearing bold

### ISSUE THREAD

**Issue by lpsantana** [JayTWWM/Quiz-View-Flutter#2]
Always the correct answer appear with the text in BOLD

**Comment by JayTWWM** [comment]
I am so sorry, I messed this up in the new update, will fix it ASAP!

**Comment by lpsantana** [comment]
Thank you SO MUCH for the fast response on this problem! Very nice from you guy, send paypal

**Comment by JayTWWM** [comment]
I don't use PayPal, is Paytm okay or should I make a PayPal??
Or maybe UPI?

**Comment by lpsantana** [comment]
I think paypal is more easy to me. Gonna send 10 dolars. sorry cant send more. In my country dollar worth to much

**Comment by JayTWWM** [comment]
[paypal.me/jaytwwm](http://paypal.me/jaytwwm) this is my Paypal, thanks man 10 dollars means lot to me.

**Comment by JayTWWM** [comment]
Fixed the issue in the latest update 1.0.5!

**Comment by lpsantana** [comment]
In a few days you will receive! Thanks, bro
